[package]
name = "forgeyard-config"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later OR Commercial"

[dependencies]
forgeyard-model = { path = "../forgeyard-model" }
serde = { workspace = true }
ron = { workspace = true }
thiserror = { workspace = true }
camino = { workspace = true }
config = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9.34"
